export const PRIMERA_PREGUNTA = 'PRIMERA_PREGUNTA';
export const SEGUNDA_PREGUNTA = 'SEGUNDA_PREGUNTA';
export const TERCERA_PREGUNTA = 'TERCERA_PREGUNTA';
export const CUARTA_PREGUNTA = 'CUARTA_PREGUNTA';
export const QUINTA_PREGUNTA = 'QUINTA_PREGUNTA';